# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  subscriptionid: b69c2a11-bd8a-4349-b9d9-1c55bd839199


jobs:
  armDeployStaginig:
    name: Deply to staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stggithubactions
      location: West US 2    
    environment:
      name:staging
    steps:
      - uses : actions/checkout@v2   

      - name : Azure Login
        uses : Azure/login@v1
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS}}
      
      - name: Deploy Resource Group ${{env.resource_group_name}}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionid: ${{env.subscriptionid}}
          region: "${{env.location}}"
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourcegroupname=${{env.resource_group_name}}
            location="${{env.location}}"
          deploymentname: ${{env.resource_group_name}}


      - name: Deploy storageaccount globostorage
        id: storageaccountdeploy
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupname: ${{env.resource_group_name}}
          subscriptionid: ${{env.subscriptionid}}
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageaccountname=m2storageaccot1984
            location="${{env.location}}"
            sku=Standard_LRS
          deploymentmode: incremental
      
      - name: Deploy Ubuntu VM
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupname: ${{env.resource_group_name}}
          subscriptionid: ${{env.subscriptionid}}
          template: ./arm-templates/virtualmachine.json
          parameters: 
             adminpassword=${{secrets.UBUNTU_ADMIN_PWD}}
             location="${{env.location}}"
          deploymentmode: incremental

  armDeployProduction:
    name: Deply to Production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-Prodgithubactions
      location: East US
    environment:
      name:production
    needs: armDeployStaginig
    steps:
      - uses : actions/checkout@v2   

      - name : Azure Login
        uses : Azure/login@v1
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS}}
      
      - name: Deploy Resource Group ${{env.resource_group_name}}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionid: ${{env.subscriptionid}}
          region: "${{env.location}}"
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourcegroupname=${{env.resource_group_name}}
            location="${{env.location}}"
          deploymentname: ${{env.resource_group_name}}


      - name: Deploy storageaccount globostorage
        id: storageaccountdeploy
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupname: ${{env.resource_group_name}}
          subscriptionid: ${{env.subscriptionid}}
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageaccountname=m2storageaccot1985
            location="${{env.location}}"
            sku=Standard_LRS
          deploymentmode: incremental
      
      - name: Deploy Ubuntu VM
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupname: ${{env.resource_group_name}}
          subscriptionid: ${{env.subscriptionid}}
          template: ./arm-templates/virtualmachine.json
          parameters: 
             adminpassword=${{secrets.UBUNTU_ADMIN_PWD}}
             location="${{env.location}}"
          deploymentmode: incremental      