# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  armDeploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses : actions/checkout@v2   

      - name : Azure Login
        uses : Azure/login@v1
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Deploy Azure Resource Group 
      - uses: Azure/arm-deploy@v1
        with:
          scope: Subscription
          SubscriptionID : b69c2a11-bd8a-4349-b9d9-1c55bd839199
          region: "west us 2"
          template: ./arm-templates/resourcegroup.json
          parameters:   
            location = "west us 2"
            resourcegroupname = rg-githubaction
          deploymentname: rg-githubaction
